### ISSUE TITLE
Once v1.0.0 is ready, "market" it on HN (of course!)

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/desktop.yml#25]

**Comment by andremillet** [comment]
Don't know if matters, but, when installing gamer's persona, got the following alert after running the oriented code:
`E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.`

A few seconds later, whitout any input, code run for it self

**Comment by andremillet** [comment]
`andremillet@andre-openemr:~$ cd ~/Desktop/System/personas/gamer && ./gamer.sh
[sudo] password for andremillet: 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://br.archive.ubuntu.com/ubuntu bionic InRelease   
Get:3 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease [15,3 kB]
Hit:4 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:6 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic/main amd64 Packages [1.468 B]
Get:7 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic/main i386 Packages [1.468 B]
Get:8 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic/main Translation-en [688 B]
Fetched 19,0 kB in 7s (2.731 B/s)                            
Reading package lists... Done
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease   
Hit:4 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
discord 0.0.5 from Snapcrafters installed
Get:1 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease [15,9 kB]
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease          
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease       
Get:6 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic/main i386 Packages [552 B]
Hit:7 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease     
Get:8 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic/main amd64 Packages [1.312 B]
Get:9 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic/main Translation-en [580 B]
Fetched 18,3 kB in 5s (3.935 B/s)
Reading package lists... Done
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease   
Hit:2 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease               
Hit:4 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease           
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]
Hit:2 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease         
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Get:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease [15,4 kB]
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:7 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease
Get:8 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic/main i386 Packages [856 B]
Get:9 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic/main Translation-en [392 B]
Fetched 99,9 kB in 5s (21,7 kB/s)
Reading package lists... Done
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]
Hit:2 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease     
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:6 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease           
Hit:7 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease
Fetched 83,2 kB in 3s (26,0 kB/s)                  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
./gamer.sh: line 32: /etc/apt/sources.list.d/FrodeSolheim-stable.list: Permission denied
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]
Hit:2 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease         
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:6 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:7 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease
Fetched 83,2 kB in 3s (28,7 kB/s)                  
Reading package lists... Done
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
quadrapassel 3.22.0 from Canonical✓ installed
xonotic 0.8.2 from Snapcrafters installed
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Hit:1 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]    
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Ign:6 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic InRelease
Hit:7 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease     
Hit:8 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease           
Err:9 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release     
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                  
E: The repository 'http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Hit:1 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]    
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease       
Ign:6 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic InRelease
Hit:7 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease     
Hit:8 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease           
Err:9 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release    
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Hit:1 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]    
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Get:6 http://ppa.launchpad.net/materieller/teamspeak3/ubuntu bionic InRelease [15,9 kB]
Hit:7 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease
Ign:8 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic InRelease
Hit:9 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease
Err:10 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release    
  404  Not Found [IP: 91.189.95.83 80]
Get:11 http://ppa.launchpad.net/materieller/teamspeak3/ubuntu bionic/main amd64 Packages [1.184 B]
Get:12 http://ppa.launchpad.net/materieller/teamspeak3/ubuntu bionic/main Translation-en [380 B]
Reading package lists... Done                                                  
E: The repository 'http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Hit:1 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]    
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease       
Hit:6 http://ppa.launchpad.net/materieller/teamspeak3/ubuntu bionic InRelease
Hit:7 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Ign:8 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic InRelease
Hit:9 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease
Err:10 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release    
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                  
E: The repository 'http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]
Hit:2 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease     
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:6 http://ppa.launchpad.net/materieller/teamspeak3/ubuntu bionic InRelease
Hit:7 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease     
Get:8 http://ppa.launchpad.net/mumble/release/ubuntu bionic InRelease [15,4 kB]
Ign:9 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic InRelease   
Hit:10 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease                
Err:11 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release    
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                  
E: The repository 'http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]
Hit:2 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease         
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:4 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:5 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:6 http://ppa.launchpad.net/materieller/teamspeak3/ubuntu bionic InRelease
Hit:7 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:8 http://ppa.launchpad.net/mumble/release/ubuntu bionic InRelease
Ign:9 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic InRelease  
Hit:10 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease                
Err:11 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release    
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                  
E: The repository 'http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Run hook prepare-slot-gsettings of snap "core"                                 |error: change finished in status "Undone" with no error message
--2018-09-19 09:17:14--  http://deb.playonlinux.com/playonlinux_precise.list
Resolving deb.playonlinux.com (deb.playonlinux.com)... 51.254.83.230, 2001:41d0:2:37ca::1e
Connecting to deb.playonlinux.com (deb.playonlinux.com)|51.254.83.230|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 45
Saving to: ‘/etc/apt/sources.list.d/playonlinux.list’

/etc/apt/sources.li 100%[===================>]      45  --.-KB/s    in 0s      

2018-09-19 09:17:16 (2,05 MB/s) - ‘/etc/apt/sources.list.d/playonlinux.list’ saved [45/45]

Hit:1 http://ppa.launchpad.net/dolphin-emu/ppa/ubuntu bionic InRelease         
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [83,2 kB]    
Hit:3 http://br.archive.ubuntu.com/ubuntu bionic InRelease                     
Get:4 http://deb.playonlinux.com precise InRelease [2.592 B]                   
Err:4 http://deb.playonlinux.com precise InRelease                       
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 73F0D6E88E3D6C3A
Hit:5 http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu bionic InRelease
Hit:6 http://br.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:7 http://ppa.launchpad.net/materieller/teamspeak3/ubuntu bionic InRelease  
Hit:8 http://br.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:9 http://ppa.launchpad.net/mumble/release/ubuntu bionic InRelease          
Ign:10 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic InRelease 
Hit:11 http://ppa.launchpad.net/wfg/0ad/ubuntu bionic InRelease                
Err:12 http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release    
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                  
W: GPG error: http://deb.playonlinux.com precise InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 73F0D6E88E3D6C3A
E: The repository 'http://deb.playonlinux.com precise InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/mzahniser/endless-sky/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Cloning into 'games'...
remote: Counting objects: 1740, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 1740 (delta 8), reused 26 (delta 7), pack-reused 1712
Receiving objects: 100% (1740/1740), 460.67 KiB | 1.16 MiB/s, done.
Resolving deltas: 100% (543/543), done.`

**Comment by MatthewVi** [comment]
@andremillet That is bad. Looking into it! Thanks for the bug report
